.bail ON
.mode columns
.headers on
.nullvalue NULL
PRAGMA foreign_keys = ON;

/*1.LISTAR CLIENTES POR ORDEM  ALFABETICA*/
.width 8 20
SELECT DISTINCT PESSOA.idPessoa AS ID, PESSOA.nome AS Nome
FROM PESSOA 
INNER JOIN CLIENTE 
ON PESSOA.idPessoa=CLIENTE.idCliente 
ORDER BY Nome
ASC;

/*2.SALARIO MEDIO DOS FUNCIONARIOS POR FUNCAO DESEMPENHADA*/
.width 20 12
SELECT TIPODEFUNCAO.nome AS Funcao, AVG(FUNCIONARIO.salario) AS SalarioMedio
FROM TIPODEFUNCAO
INNER JOIN FUNCIONARIO
ON FUNCIONARIO.idTipoDeFuncao=TIPODEFUNCAO.idTipoDeFuncao
GROUP BY Funcao;

/*3.PESQUISA DE PESSOA POR NIF COM O NUMERO 10*/
.width 11 18
SELECT DISTINCT PESSOA.nif AS NIF, PESSOA.nome AS Nome
FROM PESSOA 
WHERE PESSOA.nif 
LIKE '%10%';

/*4.NUMERO DE OCORRENCIAS DE 1 ITINERARIO NUM DIA ENTRE DUAS HORAS*/
.width 20 
SELECT COUNT(*) AS Numero_Ocorrencias
FROM OCORRENCIA 
WHERE OCORRENCIA.dataOcorr='2016-04-20'
AND OCORRENCIA.idItinerario='1'
AND OCORRENCIA.hora 
BETWEEN '09:25:00'
AND '12:30:00';

/*5.NUMERO DE VEZES ITINERARIOS QUE PASSAM NA CIDADE DE AMARANTE NO DIA 2016-04-20*/
.width 25
SELECT COUNT(*) AS N_Itinerarios_Amarante
FROM ITINERARIOESTACAO 
INNER JOIN ITINERARIO
ON ITINERARIO.idItinerario=ITINERARIOESTACAO.idItinerario
INNER JOIN OCORRENCIA
ON OCORRENCIA.idItinerario=ITINERARIOESTACAO.idItinerario
INNER JOIN ESTACAO 
ON ESTACAO.idEstacao=ITINERARIOESTACAO.idEstacao 
INNER JOIN CIDADE 
ON ESTACAO.idCidade=CIDADE.idCidade 
WHERE CIDADE.nome='Amarante' 
AND OCORRENCIA.dataOcorr='2016-04-20';

/*6.FUNCIONARIOS QUE TAMBEM SAO CLIENTES*/
.width 20
SELECT PESSOA.nome AS Nome
FROM PESSOA 
INNER JOIN CLIENTE 
ON PESSOA.idPessoa=CLIENTE.idCliente 
INTERSECT 
SELECT PESSOA.nome 
FROM PESSOA 
INNER JOIN FUNCIONARIO
ON PESSOA.idPessoa=FUNCIONARIO.idFuncionario;

/*7.FUNCIONARIOS OU CLIENTES QUE NASCERAM ANTES DE 2000-01-01*/
.width 20 20
SELECT PESSOA.nome AS Nome,PESSOA.dataNascimento AS DataNascimento
FROM PESSOA
GROUP BY PESSOA.nome
HAVING PESSOA.dataNascimento <= '2000-01-01';

/*8.PARAGENS DE UM ITINERARIO*/
.width 30
SELECT ESTACAO.nome AS Nome
FROM OCORRENCIA
INNER JOIN ITINERARIO
ON OCORRENCIA.idItinerario=ITINERARIO.idItinerario
INNER JOIN ITINERARIOESTACAO
ON ITINERARIO.idItinerario=ITINERARIOESTACAO.idItinerario
INNER JOIN ESTACAO
ON ESTACAO.idEstacao=ITINERARIOESTACAO.idEstacao
WHERE OCORRENCIA.dataOcorr='2016-05-21'
AND ITINERARIO.idItinerario=25;

/*9.LUGARES DE UM COMBOIO*/
SELECT SUM(CARRUAGEM.nLugares) AS N_Lugares
FROM CARRUAGEM
INNER JOIN COMBOIOCARRUAGEM
ON CARRUAGEM.idCarruagem=COMBOIOCARRUAGEM.idCarruagem
INNER JOIN COMBOIO
ON COMBOIO.idComboio=COMBOIOCARRUAGEM.idComboio
WHERE COMBOIO.idComboio=1;

/*10*/

